services:
 - type: web
   name: story-flow-generator
   env: node
   buildCommand: npm install
   startCommand: npm run dev
   envVars:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: 10000
